### ISSUE TITLE
There is a memory leak observable in MSVS.

### ISSUE THREAD

**Issue by DMA-Technologies** [DMA-Technologies/uvm-demo#2]
This issue was identified using the MSVS debugger.  

The issue likely exists in use of the UVM sequencer object, which seems to be collecting sequence items implicitly returned from a driver.

**Comment by DMA-Technologies** [comment]
This issue is implicitly visible under Linux, as running a 1,000,000,000 cycle test ultimately consumes all system memory.

**Comment by douglasjmoore** [comment]
We debugged our code for transaction(s) and sequence item(s) and all objects were being created and deleted.
The memory leak seems to be in the MSVC, SystemC reference, or UVM/SystemC reference.
Since this is outside the project's goals, there is no current plan to fix the issue.

**Comment by douglasjmoore** [comment]
Not the project's problem.
This was debugged and it appears to be in Microsoft or a reference code bug.
Beyond the scope of the project.
