### ISSUE TITLE
Update RELEASE_NOTES.md

### ISSUE THREAD

**Issue by DMA-Technologies** [DMA-Technologies/uvm-demo#3]
1. Update release notes to track on release versions.
2. Add release notes for demo.1.0.1 (or whatever the appropriate number is).
3. Include tag names in the release notes.
4. Reorganise the notes for the initial release:
   1. The SystemC library can be built based on downloaded source code and from a clone of the Accellera repository.
      * remove bug 2, as it isn't a bug.
   2. The SystemC and UVM/SystemC library builds both throw warnings.
      * create a level 1 title "SystemC and UVM/SystemC Caveats".
      * move bug 3 to new section, as we will not attempt to fix Accellera's library.
      * move bug 4 to new section, as we will not attempt to fix Accellera's library.
      * move bug 5 to new section, as the UVM/SystemC library is currently in beta state, thus we expect Accellera to fix this problem.
   3. Fix grammatic issues with the bugs.

**Comment by douglasjmoore** [comment]
This issue was handled in other matters while updating to SystemC 3.0.1 and SystemC/UVM beta6, so this issue is just closing now.
