### ISSUE TITLE
Restrict Excessive Diagnostic Printout From test-EXAMPLE-single_cycle

### ISSUE THREAD

**Issue by DMA-Technologies** [DMA-Technologies/uvm-demo#7]
The title says it all.

The excessive printout severely affects execution time of the baseline test program.

There are many lines of diagnostic printed for each cycle.  Perhaps provide a command-line argument affecting verbosity?

The culprit is likely source/TEST/EXAMPLE/single_cycle.h

Tests:

1. Successful build of `test-EXAMPLE-single_cycle`.
2. Limited printout from execution.
3. Successful execution `test-EXAMPLE-single_cycle` (all tests pass).

**Comment by DMA-Technologies** [comment]
Tested source code changes under Linux.  

1. Test passed successfully with no options.
2. Test passed successfully with option "-v".

**Comment by douglasjmoore** [comment]
Issue#7 Restrict Excessive Diagnostic Printout From test-EXAMPLE-single_cycle

Work completed  in Linux and Windows as follows:

1. Successful build of test-EXAMPLE-single_cycle.
2. Limited printout from execution. ("-v " = full debug and blank = limited)
3. Successful execution test-EXAMPLE-single_cycle (all tests pass for "do_test_evil").

**Comment by DMA-Technologies** [comment]
Merged into branch release-2.0.0.
