### ISSUE TITLE
Update for 'test-EXAMPLE-single_cycle'

### ISSUE THREAD

**Issue by douglasjmoore** [DMA-Technologies/uvm-demo#8]
Update INSTALL_WINDOWS.md
Update Project files for  'test-EXAMPLE-single_cycle' to remove the command line option from properties and up the warning to /W4
Update INSTALL_LINUX.md

**Comment by douglasjmoore** [comment]
Update and cleanup sc_wrapper.h - Increased warnings to /W4 so the warning C4121 needs to be disabled for the SystemC library to be linked in.

**Comment by DMA-Technologies** [comment]
1. Added wild-cards in the .gitignore file for the SystemC and UVM/SystemC libraries.
2. Modified `INSTALL_LINUX.md` to reflect use of:
   1. SystemC version 3.0.1.
   2. UVM/SystemC version 1.0-beta6.

**Comment by DMA-Technologies** [comment]
Merged into branch release-2.0.0.
